import React from "react"
import "storybook-addon-material-ui"
import MovieRow from "../components/MovieRow"

export default {
  title: "Movie Row",
  component: MovieRow,
}

const MovieRowTemplate = (args) => <MovieRow {...args} />

export const movieRow = MovieRowTemplate.bind({})

movieRow.args = {
  slug: "originals",
  title: "Originais do Netflix",
  items: {
    page: 1,
    results: [
      {
        backdrop_path: "/JB17sIsU53NuWVUecOwrCA0CUp.jpg",
        first_air_date: "2021-03-19",
        genre_ids: [10765, 10759, 18],
        id: 88396,
        name: "Falcão e o Soldado Invernal",
        origin_country: ["US"],
        original_language: "en",
        original_name: "The Falcon and the Winter Soldier",
        overview:
          'Após os eventos de "Vingadores: Ultimato", Sam Wilson/Falcão e Bucky Barnes/Soldado Invernal se unem em uma aventura que testa suas habilidades - e a paciência.',
        popularity: 3730.866,
        poster_path: "/w8Hi3GI4q1oR6EImrDWrAQFn8Ha.jpg",
        vote_average: 7.8,
        vote_count: 2426,
      },
      {
        backdrop_path: "/z59kJfcElR9eHO9rJbWp4qWMuee.jpg",
        first_air_date: "2014-10-07",
        genre_ids: [18, 10765],
        id: 60735,
        name: "Flash",
        origin_country: ["US"],
        original_language: "en",
        original_name: "The Flash",
        overview:
          "Barry enfrenta diversos assassinos que invadem a premiação onde ele acompanha Iris, mas os efeitos colaterais de seus novos superpoderes representam uma ameaça.",
        popularity: 1650.453,
        poster_path: "/wHa6KOJAoNTFLFtp7wguUJKSnju.jpg",
        vote_average: 7.7,
        vote_count: 7176,
      },
      {
        backdrop_path: "/qZtAf4Z1lazGQoYVXiHOrvLr5lI.jpg",
        first_air_date: "2017-01-26",
        genre_ids: [9648, 18, 80],
        id: 69050,
        name: "Riverdale",
        origin_country: ["US"],
        original_language: "en",
        original_name: "Riverdale",
        overview:
          "Enquanto tentam lidar com problemas típicos da adolescência como amor, sexo, escola e família, Archie e sua turma se envolvem em um grande mistério.",
        popularity: 1426.071,
        poster_path: "/pHcNHYPg0c2vg7qay6wjJoApUgS.jpg",
        vote_average: 8.6,
        vote_count: 10796,
      },
      {
        backdrop_path: "/mZjZgY6ObiKtVuKVDrnS9VnuNlE.jpg",
        first_air_date: "2017-09-25",
        genre_ids: [18],
        id: 71712,
        name: "The Good Doctor: O Bom Doutor",
        origin_country: ["US"],
        original_language: "en",
        original_name: "The Good Doctor",
        overview:
          "Um jovem médico com autismo começa a trabalhar em um famoso hospital. Além dos desafios da profissão, ele terá também que provar sua capacidade a seus colegas e superiores.",
        popularity: 1188.563,
        poster_path: "/jtLB7xJKcbekmOYkb5NZditBsgk.jpg",
        vote_average: 8.6,
        vote_count: 7350,
      },
      {
        backdrop_path: "/gmbsR4SvYhhj4SvLAlTKxIkFxp9.jpg",
        first_air_date: "2021-02-23",
        genre_ids: [10759, 10765],
        id: 95057,
        name: "Superman & Lois",
        origin_country: ["US"],
        original_language: "en",
        original_name: "Superman & Lois",
        overview:
          "Clark Kent (Tyler Hoechlin), o Superman, maior herói do mundo, e sua companheira Lois Lane (Elizabeth Tulloch), uma famosa jornalista, se esforçam para lidar com o estresse e as complexidades cotidianas de serem pais que trabalham na sociedade contemporânea.",
        popularity: 999.927,
        poster_path: "/6SJppowm7cdQgLkvoTlnTUSbjr9.jpg",
        vote_average: 8.3,
        vote_count: 633,
      },
      {
        backdrop_path: "/edmk8xjGBsYVIf4QtLY9WMaMcXZ.jpg",
        first_air_date: "2005-03-27",
        genre_ids: [18],
        id: 1416,
        name: "Grey's Anatomy",
        origin_country: ["US"],
        original_language: "en",
        original_name: "Grey's Anatomy",
        overview:
          "Os médicos do Grey Sloan Memorial Hospital lidam diariamente com casos e consequências de vida ou morte. É um no outro que eles encontram apoio, conforto, amizade e, às vezes, até mais que amizade... Juntos, eles descobrem o quanto a vida profissional e a pessoal podem ser complicadas e se misturarem no meio do caminho.",
        popularity: 956.691,
        poster_path: "/1HAm7sxXu9eGVvs8BIAlkCKGaTd.jpg",
        vote_average: 8.2,
        vote_count: 5704,
      },
      {
        backdrop_path: "/uro2Khv7JxlzXtLb8tCIbRhkb9E.jpg",
        first_air_date: "2010-10-31",
        genre_ids: [10759, 18, 10765],
        id: 1402,
        name: "The Walking Dead",
        origin_country: ["US"],
        original_language: "en",
        original_name: "The Walking Dead",
        overview:
          "Nos Estados Unidos pós-apocalíptico, um pequeno grupo de sobreviventes segue viajando à procura de uma nova casa longe dos mortos-vivos. O desespero por segurança e suprimentos os coloca constantemente à beira da sanidade.",
        popularity: 937.105,
        poster_path: "/reKs8y4mPwPkZG99ZpbKRhBPKsX.jpg",
        vote_average: 8,
        vote_count: 10340,
      },
      {
        backdrop_path: "/57vVjteucIF3bGnZj6PmaoJRScw.jpg",
        first_air_date: "2021-01-15",
        genre_ids: [10765, 9648, 18],
        id: 85271,
        name: "WandaVision",
        origin_country: ["US"],
        original_language: "en",
        original_name: "WandaVision",
        overview:
          "Wanda Maximoff  e Visão, um casal de super-heróis com uma vida perfeita, que começa a suspeitar que nem tudo é o que parece.",
        popularity: 853.338,
        poster_path: "/cm5xwxoWl2ZWuCKzwa0umHHsbmI.jpg",
        vote_average: 8.5,
        vote_count: 7831,
      },
      {
        backdrop_path: "/ta5oblpMlEcIPIS2YGcq9XEkWK2.jpg",
        first_air_date: "2016-01-25",
        genre_ids: [80, 10765],
        id: 63174,
        name: "Lúcifer",
        origin_country: ["US"],
        original_language: "en",
        original_name: "Lucifer",
        overview:
          "Entediado com a vida nas trevas, o diabo se muda para Los Angeles, abre um piano-bar e empresta sua sabedoria a uma investigadora de assassinatos.",
        popularity: 760.397,
        poster_path: "/vkGnVBSNpayJ1oCfyVaMvhrim95.jpg",
        vote_average: 8.5,
        vote_count: 8076,
      },
      {
        backdrop_path: "/pLG4ihU1d2XkQbASQDjsFu9U7d9.jpg",
        first_air_date: "2021-03-24",
        genre_ids: [18, 80, 9648],
        id: 120168,
        name: "Quem Matou Sara?",
        origin_country: ["MX"],
        original_language: "es",
        original_name: "¿Quién mató a Sara?",
        overview:
          "Determinado a se vingar e provar que foi falsamente incriminado pelo assassinato da irmã, Álex está prestes a descobrir muito mais do que o real culpado pelo crime.",
        popularity: 670.923,
        poster_path: "/5BYyTmEqkYXIgdDPyEiAeAbhIsI.jpg",
        vote_average: 7.9,
        vote_count: 130,
      },
      {
        backdrop_path: "/aqrvHKPWe5VedvvJIz7FWrtcoQh.jpg",
        first_air_date: "2021-03-19",
        genre_ids: [10759, 80, 18],
        id: 117023,
        name: "Sky Rojo",
        origin_country: ["ES"],
        original_language: "es",
        original_name: "Sky Rojo",
        overview:
          "Para fugir de um cafetão e seus capangas, três mulheres embarcam em uma jornada alucinante em busca da liberdade.",
        popularity: 575.132,
        poster_path: "/uTFX9V2dct1nKjG6zhNiThPm8Tp.jpg",
        vote_average: 8,
        vote_count: 120,
      },
      {
        backdrop_path: "/gL8myjGc2qrmqVosyGm5CWTir9A.jpg",
        first_air_date: "2018-05-02",
        genre_ids: [10759, 18],
        id: 77169,
        name: "Cobra Kai",
        origin_country: ["US"],
        original_language: "en",
        original_name: "Cobra Kai",
        overview:
          "Esta sequência de Karate Kid pega 30 anos depois dos eventos do All Valley Karate Tournament de 1984 e encontra Johnny Lawrence em busca de redenção reabrindo o infame dojo de karate Cobra Kai . Isso reacende sua antiga rivalidade com o bem-sucedido Daniel LaRusso, que vem trabalhado para manter o equilíbrio em sua vida sem o seu mentor Miyagi.",
        popularity: 500.153,
        poster_path: "/eTMMU2rKpZRbo9ERytyhwatwAjz.jpg",
        vote_average: 8.1,
        vote_count: 2845,
      },
      {
        backdrop_path: "/fRYwdeNjMqC30EhofPx5PlDpdun.jpg",
        first_air_date: "2018-10-25",
        genre_ids: [10765, 18],
        id: 79460,
        name: "Legados",
        origin_country: ["US"],
        original_language: "en",
        original_name: "Legacies",
        overview:
          "Hope Mikaelson, descendente da linhagem mais poderosa de vampiros, lobisomens e bruxas, frequenta a Escola Salvatore para Jovens e Superdotados, um refúgio onde ela pode aprender a controlar suas habilidades e impulsos sobrenaturais.",
        popularity: 485.366,
        poster_path: "/roFJeeBbcFYCaTfmKaCQ7wtCT5l.jpg",
        vote_average: 8.6,
        vote_count: 1728,
      },
      {
        backdrop_path: "/fPF6h8LLtZ40NRqkHfx2DvFbmkW.jpg",
        first_air_date: "2021-01-27",
        genre_ids: [10765],
        id: 96580,
        name: "Resident Alien",
        origin_country: ["US"],
        original_language: "en",
        original_name: "Resident Alien",
        overview:
          "Harry Vanderspleige é um alienígena que pousa no planeta Terra, assumindo a identidade de um médico de uma pequena cidade do Colorado para levar a cabo uma missão secreta: acabar com a humanidade.",
        popularity: 451.163,
        poster_path: "/bG5aqfT5lTHuSbcQofNHtH0RyyP.jpg",
        vote_average: 8.6,
        vote_count: 92,
      },
      {
        backdrop_path: "/wAEWZm2pSopAbqE5dQWE0ET8aR5.jpg",
        first_air_date: "2021-01-08",
        genre_ids: [99],
        id: 114695,
        name: "Lendas da Marvel",
        origin_country: ["US"],
        original_language: "en",
        original_name: "Marvel Studios: Legends",
        overview:
          "Revisite os heróis, vilões e momentos épicos de todo o MCU em preparação para as histórias altamente esperadas que ainda estão por vir.",
        popularity: 444.363,
        poster_path: "/5GKRz38rqy2B45fj3T4MR6sJxAm.jpg",
        vote_average: 7.7,
        vote_count: 362,
      },
      {
        backdrop_path: "/aq2yEMgRQBPfRkrO0Repo2qhUAT.jpg",
        first_air_date: "2013-03-03",
        genre_ids: [10759, 18],
        id: 44217,
        name: "Vikings",
        origin_country: ["CA"],
        original_language: "en",
        original_name: "Vikings",
        overview:
          "Ragnar Lothbrok, um jovem que se considera descendente de Odin, é um guerreiro, fazendeiro e chefe de família. Visionário e sonhando viver diversas aventuras, ele acredita que as riquezas sonhadas por seu povo encontram-se além do mar Báltico. Mas para conseguir conquistá-las ele precisa convencer Earl Haraldson, o líder de seu povo, a permitir que ele e seus guerreiros viagem em direção à Inglaterra.",
        popularity: 432.518,
        poster_path: "/oktTNFM8PzdseiK1X0E0XhB6LvP.jpg",
        vote_average: 8,
        vote_count: 4272,
      },
      {
        backdrop_path: "/9XhJ6rsGX2bG0CBNFWwzjtPaZig.jpg",
        first_air_date: "2019-03-08",
        genre_ids: [99],
        id: 87083,
        name: "Formula 1: Dirigir para Viver",
        origin_country: ["GB"],
        original_language: "en",
        original_name: "Formula 1: Drive to Survive",
        overview:
          "Pilotos, gestores e donos de equipes vivem grandes emoções – nas pistas e fora delas – durante uma implacável temporada de corridas de Fórmula 1.",
        popularity: 406.463,
        poster_path: "/nS7zz9clFz4WfXCvffMEbDLFIvC.jpg",
        vote_average: 8.3,
        vote_count: 75,
      },
      {
        backdrop_path: "/suopoADq0k8YZr4dQXcU6pToj6s.jpg",
        first_air_date: "2011-04-17",
        genre_ids: [10765, 18, 10759],
        id: 1399,
        name: "Game of Thrones",
        origin_country: ["US"],
        original_language: "en",
        original_name: "Game of Thrones",
        overview:
          "Em uma terra onde os verões podem durar vários anos e o inverno toda uma vida, sete nobres famílias lutam pelo controle da mítica terra de Westeros, dividida depois de uma guerra. Num cenário que lembra a Europa medieval, reis, rainhas, cavaleiros e renegados usam todos os meios possíveis em um jogo político pela disputa do Trono de Ferro, o símbolo do poder absoluto.",
        popularity: 401.548,
        poster_path: "/mQ9cyw1gfpK1M3a69cgXFHvWkih.jpg",
        vote_average: 8.4,
        vote_count: 13723,
      },
      {
        backdrop_path: "/6UH52Fmau8RPsMAbQbjwN3wJSCj.jpg",
        first_air_date: "2021-03-26",
        genre_ids: [16, 10759, 18],
        id: 95557,
        name: "Invencível",
        origin_country: ["US"],
        original_language: "en",
        original_name: "Invincible",
        overview:
          "INVENCÍVEL é uma animação de super-heróis para adultos e conta a história de Mark Grayson, de 17 anos, um cara como qualquer outro de sua idade, exceto que seu pai é o super-herói mais poderoso do planeta, Omni-Man. Porém, à medida que Mark desenvolve seus próprios poderes, ele descobre que o legado de seu pai pode não ser tão heroico quanto parece.",
        popularity: 390.335,
        poster_path: "/yDWJYRAwMNKbIYT8ZB33qy84uzO.jpg",
        vote_average: 8.8,
        vote_count: 178,
      },
      {
        backdrop_path: "/Aof7R1if9jKhHCk6M7UGyEQWQSk.jpg",
        first_air_date: "2018-10-16",
        genre_ids: [80, 18],
        id: 79744,
        name: "The Rookie",
        origin_country: ["US"],
        original_language: "en",
        original_name: "The Rookie",
        overview:
          "John Nolan, de 40 anos, muda sua vida para ser um agente policial no Departamento de Polícia de Los Angeles.",
        popularity: 380.463,
        poster_path: "/arPUIveaNTdlZeSrOPrgof6UvhQ.jpg",
        vote_average: 8,
        vote_count: 422,
      },
    ],
    total_pages: 500,
    total_results: 10000,
  },
}
